### ISSUE TITLE
Operation rejected by the mempool pre filter

### ISSUE THREAD

**Issue by muhazzz** [cryptiumlabs/backerei#21]
When running `bakcerei payout --no-dry-run` I get the following error:
```
backerei: VanillaHttpException (HttpExceptionRequest Request {
  host                 = "mainnet_node_1"
  port                 = 8732
  secure               = False
  requestHeaders       = [("Content-Type","application/json")]
  path                 = "/injection/operation"
  queryString          = ""
  method               = "POST"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutMicro 600000000
  requestVersion       = HTTP/1.1
}
 (StatusCodeException (Response {responseStatus = Status {statusCode = 500, statusMessage = "Internal Server Error"}, responseVersion = HTTP/1.1, responseHeaders = [("content-length","128"),("content-type","application/json")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) "[{\"kind\":\"generic\",\"error\":\"Operation ooJwwWtBZfGUTZ9fa33GSmiJV1tTcYQgfP7scZptf413HVAtxic rejected by the mempool pre filter\"}]\n"))
```
My .backerei.json config:
```
fromAddress: tz1Payer.....
fromAccountName: acc-pay
databasePath: /etc/backerei/.backerei.json
fee:
  denominator: 10
  numerator: 1
cycleLength: 4096
clientPath: /home/opam/opam-repository/tezos/tezos-client
clientConfigFile: /home/opam/.tezos-client/config
startingCycle: 8
host: mainnet_node_1
snapshotInterval: 256
bakerAddress: tz1Baker....
port: 8732
```
I have revealed the tz1Payer..... and tried to send tokens with `tezos-client` from tz1Payer.... to another address — everything works fine. But `backerei payout --no-dry-run` still does not work: `Operation ooJwwWtBZfGUTZ9fa33GSmiJV1tTcYQgfP7scZptf413HVAtxic rejected by the mempool pre filter` (see the full error text above)

What's wrong and what should I do to fix it?
