### ISSUE TITLE
Err 500 - unknown seed

### ISSUE THREAD

**Issue by Resilioh** [cryptiumlabs/backerei#24]
Hello,

When running `backerei payout` this message shows : 
```
backerei: VanillaHttpException (HttpExceptionRequest Request {
  host                 = "127.0.0.1"
  port                 = 8732
  secure               = False
  requestHeaders       = []
  path                 = "/chains/main/blocks/head/helpers/baking_rights"
  queryString          = "?delegate=tz1xx&cycle=38"
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutMicro 600000000
  requestVersion       = HTTP/1.1
}
```
And the error : 

`(StatusCodeException (Response {responseStatus = Status {statusCode = 500, statusMessage = "Internal Server Error"}, responseVersion = HTTP/1.1, responseHeaders = [("content-length","212994"),("content-type","application/json")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) "[{\"kind\":\"permanent\",\"id\":\"proto.003-PsddFKi3.seed.unknown_seed\",\"oldest\":30,\"requested\":38,\"latest\":36},{\"kind\":\"permanent\",\"id\":\"proto.003-PsddFKi3.seed.unknown_seed\",\"oldest\":30,\"requested\":38,\"latest\":36},{\"kind\":\"permanent\",\"id\":\"proto.003-PsddFKi3.seed.unknown_seed\",\"oldest\":30,\"requested\":38,\"latest\":36},{\"kind\":\"permanent\",\"id\":\"proto.003-PsddFKi3.seed.unknown_seed\",\"oldest\":30,\"requested\":38,\"latest\":36},{\"kind\":\"permanent\",\"id\":\"proto.003-PsddFKi3.seed.unknown_seed\",\"oldest\":30,\"requested\":38,\"latest\":36},{\"kind\":\"permanent\",\"id\":\"proto.003-PsddFKi3.seed.unknown_seed\",\"oldest\":30,\"requested\":38,\"latest\":36},{\"kind\":\"permanent\",\"id\":\"proto.003-PsddFKi3.seed.unknown_seed\",\"oldest\":30,\"requested\":38,\"latest\":36},{\"kind\":\"permanent\",\"id\":\"proto.003-PsddFKi3.seed.unknown_seed\",\"oldest\":30,\"requested\":38,\"latest\":36},{\"kind\":\"permanent\",\"id\":\"proto.003-PsddFKi3.seed.unknown_seed\",\"oldest\":30,\"requested\":38,\"latest\":36},{\"kind\":\"permanent\",\"id\":\"proto.003-PsddFKi3.seed.unknown_seed\",\"oldest\":30,\"requested\""))`

My .backerei.yaml config file : 
```
fromAddress: tz1xx
fromAccountName: name
databasePath: /home/user/.backerei.json
fee:
  denominator: 10
  numerator: 1
cycleLength: 4096
clientPath: /home/user/Documents/tezos/tezos-client
clientConfigFile: /home/user/.tezos-client/config
startingCycle: 38
host: 127.0.0.1
snapshotInterval: 256
bakerAddress: tz1xx
port: 8732
```

I looked at tezos RPC Errors : https://tezos.gitlab.io/alphanet/api/errors.html
It shows : 
> The requested seed is not available

I'm thinking this issue concerns the cycle. Is it normal that the latest is lower than the requested, whatever the starting cycle is. I'm on the alphanet. 

Thanks for help,

**Comment by cwgoes** [comment]
You've configured a starting cycle which seems to be higher than the cycle your node is synced to or has available.

**Comment by Resilioh** [comment]
Cycle changed, I tried every possibilities in the range 1-50. Nothing works. 
If too low : `backerei: should not happen: tezos rpc fault, wrong level `
If normal : Err 500 unknown seed
If too high : no message nothing happens.

So I'm wondering, is backerei using tzscan.io api ? If yes, tzscan api does not work on the alphanet.

Thanks @cwgoes

**Comment by cwgoes** [comment]
Backerei does not use the Tzscan API; it connects only to the node you specify.

Have you changed the cycle length and snapshot interval to the correct parameters for the alphanet?

**Comment by Jovi1945** [comment]
Does the cycle that you would like to begin payouts in have to be completed for "bäckerei payout --no-dry-run" to actually pay out?

**Comment by cwgoes** [comment]
Yes - `backerei` will send payouts as soon as they have been released by the Tezos protocol (five cycles after the baking / endorsing events).

**Comment by Trappist8** [comment]
Thank you @cwgoes

**Comment by Resilioh** [comment]
Late, sorry
so I tried with the right cycle length and snapshot : 
```
fromAddress: tz1xx
fromAccountName: name
databasePath: /home/user/.backerei.json
fee:
  denominator: 10
  numerator: 1
cycleLength: 2048
clientPath: /home/user/Documents/tezos/tezos-client
clientConfigFile: /home/user/.tezos-client/config
startingCycle: 38
host: 127.0.0.1
snapshotInterval: 128
bakerAddress: tz1xx
port: 8732
```
This time, it displays an "internal error 500", but the cause is different : "missing key" (even if the manager key has been revealed).
However I stopped using the alphanet, and tried Backerei on the Mainnet and it works fine.
