### ISSUE TITLE
backerei: Prelude.last: empty list

### ISSUE THREAD

**Issue by jrhite** [cryptiumlabs/backerei#34]
When I run backerei with `.backerei.yaml` with a setting of `startingCycle: 75` which is my baker's real staring cycle I get this error:

```
$ backerei payout
Enter source account password: 
Creating new DB in file /home/bakerei_payer/.backerei.json...
Updating DB with estimates for cycle 75...
backerei: Prelude.last: empty list
```

I played around with the starting cycle number to try to debug a little. When I changed the starting cycle to 74 I see an error, which makes sense, since my baker didn't exist then:
```
backerei: VanillaHttpException (HttpExceptionRequest Request {
  host                 = "127.0.0.1"
  port                 = 8732
  secure               = False
  requestHeaders       = []
  path                 = "/chains/main/blocks/BMSaVj45hWuPVX51zvxJUUXR59Lk5agbnzKe94N7HYAmKUNWgvo/context/delegates/tz1XXXXXXXXXXXXX/balance"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutMicro 600000000
  requestVersion       = HTTP/1.1
}
```

When I changed the starting cycle to 90 things work, but the starting cycle isn't accurate. This is probably inconsequential, but still seems like a bug.

**Comment by tzemanovic** [comment]
What's your setting for the fee? I suspect you might need to set the fee for this (or lower cycle) if you initialized with a higher starting cycle.

**Comment by jrhite** [comment]
This is my `.backerei.yaml` file. I'm assuming anything not specified here would default to something reasonable, or do I need to add some extra config variables?

```
fees:
- - 90
  - denominator: 10
    numerator: 1
fromAddress: KT1xxx
fromAccountName: Howdy there
databasePath: /home/bakerei_payer/.backerei.json
cycleLength: 4096
clientPath: /home/bakerei_payer/tezos/tezos-client
clientConfigFile: /home/bakerei_payer/.tezos-client/config

# the true first starting cycle of this baker, but this causes the error:
# Prelude.last: empty list
#startingCycle: 75 

startingCycle: 90
host: 127.0.0.1
snapshotInterval: 256
bakerAddress: tz1xxx
port: 8732
```
